# logLevel: <number>
logLevel: 2

# path: <string>
path: /var/run/mirakurun.sock

# port: <number>
# You can change this if port conflicted.
# Don't expose this port on the internet, not even with NAPT.
# Use this in LAN or VPN.
# `~` to disable TCP port listening.
port: 40772

# http://nodoka.org/mirakurun-%E3%83%90%E3%83%83%E3%83%95%E3%82%A1-%E6%9E%AF%E6%B8%87%E9%9A%9C%E5%AE%B3-%E5%AF%BE%E7%AD%96%E7%B7%A8/
highWaterMark: 268435456

