- name: PX4-T1
  types:
    - GR
  command: recdvb --dev 0 --b25 --strip <channel> - -

- name: PT4-T2
  types:
    - GR
  command: recdvb --dev 1 --b25 --strip <channel> - -

- name: PT4-T3
  types:
    - GR
  command: recdvb --dev 2 --b25 --strip <channel> - -

- name: PT4-T4
  types:
    - GR
  command: recdvb --dev 3 --b25 --strip <channel> - -

#- name: PT3-S1
#  types:
#    - BS
#    - CS
#  command: recpt1 --device /dev/pt3video0 --lnb 15 <channel> - -
#  decoder: arib-b25-stream-test
#  isDisabled: true
#
#- name: PT3-S2
#  types:
#    - BS
#    - CS
#  command: recpt1 --device /dev/pt3video1 --lnb 15 <channel> - -
#  decoder: arib-b25-stream-test
#  isDisabled: true
#
#- name: PT3-T1
#  types:
#    - GR
#  command: recpt1 --device /dev/pt3video2 <channel> - -
#  decoder: arib-b25-stream-test
#  isDisabled: true
#
#- name: PT3-T2
#  types:
#    - GR
#  command: recpt1 --device /dev/pt3video3 <channel> - -
#  decoder: arib-b25-stream-test
#  isDisabled: true
#
#- name: TBS6922
#  types:
#    - SKY
#  command: szap-s2j -c /usr/local/etc/szap-s2j.conf -l <satelite> -S 1 -p -r -M 5 -C 35 <channel>
#  dvbDevicePath: /dev/dvb/adapter0/dvr0
#  decoder: arib-b1-stream-test
#  isDisabled: true

